export interface User {
  id: number
  email: string
  username: string
  address: string
  lastLogin: Date
  zip: string
  gender: string
  category: string
  paidThru: Date
  spin: null
  firstName: string
  lastName: string
  mi: string
  name: string
  birthDate: Date
  IsDobVerified: boolean
  cellPhone: string
  homePhone: string
  workPhone: null
  imisId: string
  IsCodeOfConductSigned: boolean
  IsCitizenshipVerified: boolean
  citizenship: string
  profilePictureUrl: null
  mainAffiliation: MainAffiliation
  TSize: string
  isStaffAdmin: boolean
  address1: string
  address2: string
  city: string
  state: string
  stateId: null
  countryCode: string
  isFacebookUser: boolean
  isFacebookDedicatedAccount: boolean
  isGoogleUser: boolean
  isGoogleDedicatedAccount: boolean
  rtoId: null
  PlayerId: number
  TITLE: null
  COMPANY: null
  PREFIX: null
  SUFFIX: null
  DESIGNATION: null
  INFORMAL: null
  PAID_THRU: Date
  WEBSITE: null
  CHAPTER: null
  hideScoringPopup: boolean
  profileBackgroundUrl: string
  coachingInterest: boolean
  officialInterest: boolean
  PlayerID: null
  FrontPage: null
  ShowGender: null
  ShowHomePhone: null
  ShowWorkPhone: null
  ShowCellPhone: null
  ShowEmail: null
  UserUpdated: null
  HideProfileInfo: null
  PreferredCommunication: null
  PreferredPhone: null
  OptOut_Magazine: null
  OptOut_Mail: null
  OptOut_Email: null
  OptOut_Text: null
  OptOut_3rdParty: null
  TimeZone: null
  Notification_Tournament: null
  Show_Location: null
  accountVerified: boolean
  fullyVaccinated: null
  isMember: boolean
  affiliations: HomeClub[]
  homeClub: HomeClub
}

export interface HomeClub {
  isHome: string
  id: number
  Affiliationid: number
  AffiliationName: string
  name: string
  type: number
  City: string
  TypeID: number
  clubLogo: string
  districtLogo: string
}

export interface MainAffiliation {
  id: number
  descr: string
  shortName: string
  URL: string
  TypeID: number
  City: string
  LogoImageUrl: string
  urlTitle: string
  SupportLink: string
  BackgroundImageUrl: string
  expDate: Date
  customId: number
}
